version: '3.7'

services:
  api:
    build: .
    command: yarn server
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/src/webapi
      - /usr/src/webapi/node_modules
    container_name: devRadar-api
    depends_on:
      - db
    links:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo-container
